export const ActionTypes = {
    GET_USER_SUCCESS : "GET_USER_SUCCESS",
    GET_USER_PENDING : "GET_USER_PENDING",
    GET_USER_FAIL : "GET_USER_FAIL",

    
    GET_POST_SUCCESS : "GET_POST_SUCCESS",
    GET_POST_PENDING : "GET_POST_PENDING",
    GET_POST_FAIL : "GET_POST_FAIL",
} 

